# Generated by Django 3.2.6 on 2021-08-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='count_of_pages',
        ),
    ]
